import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createRound } from './questions';
import './styles.css';
import './theme.css';

const years = ['Foundations', 'Building blocks', 'Systems & networks', 'Embedded & real-time', 'Engineering at scale'];
const levels = ['beginner', 'intermediate', 'advanced'];
function Icon({ type = 'arrow', ...props }) {
  const paths = { arrow: 'M5 12h14m-6-6 6 6-6 6', bolt: 'm13 2-9 12h7l-1 8 10-13h-7l1-7', code: 'm8 6-6 6 6 6m8-12 6 6-6 6m-3-14-2 16', grid: 'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z', check: 'm5 12 4 4L19 6', home: 'm3 10 9-7 9 7v11h-6v-7H9v7H3z' };
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><path d={paths[type]} /></svg>;
}
function App() {
  const [screen, setScreen] = useState('home');
  const [year, setYear] = useState(1);
  const [level, setLevel] = useState('beginner');
  const [round, setRound] = useState([]);
  const [answers, setAnswers] = useState([]);
  const [selected, setSelected] = useState(null);
  const [review, setReview] = useState(false);
  const dialog = useRef(null);
  const heading = useRef(null);
  const index = answers.length;
  const score = answers.filter((a, i) => a === round[i]?.correct).length;
  useEffect(() => { if (screen === 'result') dialog.current?.showModal(); else heading.current?.focus(); }, [screen]);
  function home() { setScreen('home'); setReview(false); }
  function start() { setRound(createRound(year, level)); setAnswers([]); setSelected(null); setReview(false); setScreen('quiz'); }
  function next() { if (selected === null) return; setAnswers([...answers, selected]); setSelected(null); if (index === 4) setScreen('result'); else requestAnimationFrame(() => heading.current?.focus()); }
  const active = screen === 'quiz' || screen === 'result';
  return <div className="app-shell">
    <header className="header"><button className="brand" onClick={home} aria-label="CSE Arcade home"><img src="/logo.png" alt=""/><span>CSE<span className="brand-light"> ARCADE</span></span></button><nav aria-label="Main navigation"><button className={screen === 'home' ? 'nav-active' : ''} onClick={home}><Icon type="grid"/>The arcade</button><span className="status"><i/> READY TO PLAY</span></nav></header>
    <main>
      {screen === 'home' ? <>
        <section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="tiny-line"/> A LITTLE PLAY. A LOT OF POSSIBILITY.</span><h1 ref={heading} tabIndex="-1">Your next<br/>level starts <em>here.</em></h1><p>A playground for curious engineers. Put your knowledge to the test, challenge yourself, and learn as you play.</p><a className="primary" href="#games">Find your challenge <Icon/></a><div className="hero-notes"><span><Icon type="bolt"/> Quick rounds</span><span><Icon type="code"/> Built for CSE minds</span></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="art-code code-one">&lt;/&gt;</span><span className="art-code code-two">01</span><span className="art-plus">+</span><img src="/logo.png" alt="Computer Systems Engineering club dragon logo"/><span className="art-label"><i/> ENGINEER YOUR NEXT LEVEL</span></div></section>
        <section id="games" className="games"><div className="section-heading"><div><span className="eyebrow">CHOOSE YOUR CHALLENGE</span><h2>The game room<span>.</span></h2></div><span className="game-count">01 GAME AVAILABLE</span></div><button className="game-card" onClick={() => setScreen('year')}><div className="game-art"><div className="question-tile">?<span>_</span></div><span className="mini-code">if (curious) &#123; play(); &#125;</span><span className="art-corner">01 / CSE</span></div><div className="game-info"><span className="tag"><i/> KNOWLEDGE CHALLENGE</span><h3>The Questions Game</h3><p>Small questions. Big brain energy.<br/>Five questions, tailored to your year and skill level.</p><div className="game-meta"><span>5 questions</span><span>5 years</span><span>3 skill levels</span></div><span className="play-link">Let’s play <Icon/></span></div><span className="card-number">01</span></button><div className="coming-soon"><span className="plus-box">+</span><div><strong>More ways to play, on the way.</strong><p>The arcade is just getting started.</p></div><span className="outline-tag">STAY CURIOUS</span></div></section>
      </> : <section className="play-area"><button className="back" onClick={() => screen === 'level' ? setScreen('year') : home()}>← {screen === 'level' ? 'Choose year' : 'Back to arcade'}</button><div className="play-topline"><span className="eyebrow">THE QUESTIONS GAME</span><span className="round-badge">{active ? `YEAR ${year} / ${level.toUpperCase()}` : 'BUILD YOUR CHALLENGE'}</span></div>
        {screen === 'year' && <><h1 ref={heading} tabIndex="-1" className="screen-title">Where are you at<span>?</span></h1><p className="subtitle">Pick your study year. We’ll meet you at your level.</p><div className="year-grid">{years.map((name, i) => <button key={name} className={`year-card ${year === i + 1 ? 'chosen' : ''}`} onClick={() => setYear(i + 1)} aria-pressed={year === i + 1}><span className="year-digit">0{i + 1}</span><strong>Year {i + 1}</strong><span>{name}</span><span className="selection-dot">{year === i + 1 && <Icon type="check" width="14" height="14"/>}</span></button>)}</div><div className="step-footer"><span>STEP 01 <span className="muted">/ 02</span></span><button className="primary" onClick={() => setScreen('level')}>Choose proficiency <Icon/></button></div></>}
        {screen === 'level' && <><h1 ref={heading} tabIndex="-1" className="screen-title">Set your challenge<span>.</span></h1><p className="subtitle">Year {year} · {years[year - 1]}. How far will you push yourself?</p><div className="level-grid">{levels.map((name, i) => <button key={name} className={`level-card ${level === name ? 'chosen' : ''}`} onClick={() => setLevel(name)} aria-pressed={level === name}><div className="bars">{[0, 1, 2].map(n => <i key={n} className={n <= i ? 'lit' : ''}/>)}</div><h2>{name}</h2><p>{['Get comfortable with the essentials.', 'Connect concepts and apply what you know.', 'Go deeper with tricky concepts and calculations.'][i]}</p><span className="selection-dot">{level === name && <Icon type="check" width="14" height="14"/>}</span></button>)}</div><div className="step-footer"><span>STEP 02 <span className="muted">/ 02 · 5 QUESTIONS · NO TIMER</span></span><button className="primary" onClick={start}>Start playing <Icon type="bolt"/></button></div></>}
        {active && <><div className="quiz-progress"><span>QUESTION {Math.min(index + 1, 5)} OF 5</span><div>{[0, 1, 2, 3, 4].map(i => <i key={i} className={i <= index ? 'filled' : ''}/>)}</div></div>{screen === 'quiz' && <div className="question-panel"><h1 className="question-title" ref={heading} tabIndex="-1">{round[index].prompt}</h1><div className="options" role="group" aria-label="Answer choices">{round[index].options.map((option, i) => <button key={`${index}-${option}`} className={`option ${selected === option ? 'chosen' : ''}`} onClick={() => setSelected(option)} aria-pressed={selected === option}><span>{String.fromCharCode(65 + i)}</span>{option}<span className="option-check">{selected === option && <Icon type="check"/>}</span></button>)}</div><div className="question-footer"><span>Choose one answer. Make it count.</span><button className="primary" disabled={selected === null} onClick={next}>{index === 4 ? 'See my results' : 'Next question'}<Icon/></button></div></div>}</>}
      </section>}
    </main>
    <footer><span>CSE ARCADE <span className="footer-separator">/</span> Play. Learn. Level up.</span><span>Made for the next generation of engineers.</span></footer>
    {screen === 'result' && <dialog ref={dialog} className="result-dialog" onCancel={e => { e.preventDefault(); home(); }}><span className="eyebrow">ROUND COMPLETE</span><div className="score-ring"><strong>{score}<span>/ 5</span></strong><span>{score * 20}% CORRECT</span></div><h2>{score === 5 ? 'Perfectly engineered.' : score >= 3 ? 'Nicely played.' : 'Every round is a step up.'}</h2><p>Year {year} · <span className="capitalize">{level}</span><br/>{score === 5 ? 'You nailed every question. Ready for another challenge?' : 'Keep your curiosity going. There’s always another level.'}</p><button className="review-toggle" onClick={() => setReview(!review)} aria-expanded={review}>{review ? 'Hide' : 'Review'} answers {review ? '−' : '+'}</button>{review && <div className="answer-review">{round.map((q, i) => <div key={q.prompt}><strong><span className={answers[i] === q.correct ? 'correct' : 'incorrect'}>{answers[i] === q.correct ? '✓' : '✕'}</span> {i + 1}. {q.prompt}</strong><p>Your answer: {answers[i]}</p>{answers[i] !== q.correct && <p className="correct">Correct answer: {q.correct}</p>}</div>)}</div>}<div className="result-actions"><button className="primary" onClick={home}><Icon type="home"/>Return to home</button><button className="secondary" onClick={start}>Play again</button></div></dialog>}
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
